# Generated by Django 4.1.6 on 2023-11-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_images_post_image_alter_post_created_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentQ',
        ),
    ]
