# Generated by Django 4.1.6 on 2023-11-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_box',
            name='post_c',
        ),
    ]
