# Generated by Django 4.1.6 on 2023-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_comment_box_post_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_box',
            name='date',
        ),
    ]
