# Generated by Django 4.1.6 on 2023-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_comment_box_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=123)),
                ('content', models.TextField()),
            ],
        ),
    ]
